name: CI
on: [push, pull_request]

jobs:
  shellcheck:
    name: shellcheck
    runs-on: [ubuntu-latest]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@0.1.0

  test:
    name: Test
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        # inspired by github.com/sdolenc/bash-matrix/
        container:
          - debian:buster-slim  # deb10 bash5.0
          - debian:stretch-slim # deb09 bash4.4
          - debian/eol:jessie  # deb08 bash4.3
          # - bash:4.2
          #todo: 'bash:4.1',
          #tbd: 'bash:4.0', 'bash:3.2', 'bash:3.1', 'bash:3.0'

    container: ${{ matrix.container }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          bash --version | head -2
          scripts/test.sh
        shell: bash

  publish:
    name: Publish
    runs-on: [ubuntu-latest]
    needs: [shellcheck, test]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Publishing Docker image
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: checksum/critic.sh
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
